image: amazoncorretto:21
pipelines:
  default:
    - step:
        name: Run tests only
        caches:
          - docker
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - ./mvnw test
        services:
          - docker
  branches:
    master:
      - step:
          name: Build
          caches:
            - docker
          script:
            - IMAGE_NAME="os2compliance"
            - IMAGE_TAG="master"
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - ./mvnw test
            - docker build . -t ${IMAGE_NAME}:${IMAGE_TAG}
            - pipe: atlassian/aws-ecr-push-image:2.0.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                IMAGE_NAME: ${IMAGE_NAME}
                AWS_DEFAULT_REGION: "eu-west-1"
                TAGS: ${IMAGE_TAG}
                DEBUG: "true"
          services:
            - docker
  tags:
    release-*:
      - step:
          name: Build
          caches:
            - docker
          script:
            - IMAGE_NAME="os2compliance"
            - docker build . -t ${IMAGE_NAME}:${BITBUCKET_TAG}
            - pipe: atlassian/aws-ecr-push-image:2.2.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                IMAGE_NAME: os2compliance
                AWS_DEFAULT_REGION: "eu-west-1"
                TAGS: ${BITBUCKET_TAG}
                DEBUG: "true"
          services:
            - docker