version: '3.3'
services:
  db:
    image: mariadb:10.6.14
    environment:
      MARIADB_DATABASE: 'grcompliance'
      MARIADB_ROOT_PASSWORD: 'Test1234'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - compliance-db:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  compliance-db:
