package dk.digitalidentity.model.dto.enums;

public enum SetFieldType {
	NOT_RELEVANT, PROBABILITY, RF, RI, RT, OF, OI, OT, SF, SI, ST, SA, PROBLEM, ADDITIONAL_MEASURES, METHOD, ELABORATION, RESIDUAL_RISK_PROBABILITY, RESIDUAL_RISK_CONSEQUENCE;
}
