ALTER TABLE tasks ADD COLUMN start_date DATE NULL;
UPDATE tasks SET start_date = DATE(created_at);
ALTER TABLE tasks MODIFY COLUMN start_date DATE NOT NULL DEFAULT (CURRENT_DATE);

ALTER TABLE tasks_aud ADD COLUMN start_date DATE NULL;