ALTER TABLE tia
    ADD COLUMN accepted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN accepted_comment TEXT DEFAULT NULL,
    ADD COLUMN accepted_by_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN accepted_by_uuid VARCHAR(36) DEFAULT NULL,
    ADD COLUMN accepted_date DATE DEFAULT NULL;
