ALTER TABLE task_logs MODIFY documentation_link varchar(2048) null;
ALTER TABLE data_processing MODIFY deletion_procedure_link varchar(2048) null;
ALTER TABLE assets MODIFY product_link varchar(2048) null;
ALTER TABLE assets MODIFY emergency_plan_link varchar(2048) null;
ALTER TABLE assets MODIFY re_establishment_plan_link varchar(2048) null;
ALTER TABLE assets MODIFY contract_link varchar(2048) null;
ALTER TABLE assets MODIFY data_processing_agreement_link varchar(2048) null;
ALTER TABLE documents MODIFY link varchar(2048) null;
ALTER TABLE registers MODIFY emergency_plan_link varchar(2048) null;
